// @ts-nocheck
import { state, upgradeFlags, rechargeTimers, pickCounts } from './state';
import { GRAVITY, TYPE_ORDER } from './config';

export const PROJ_DEFS = {
  pelote: {
    label: 'Pelote', emoji: '🧶', col: '#ff8a48',
    speed: [5, 22], gravity: GRAVITY,
    stock: 3, maxStock: 3, recharge: 2,
    unlockScore: 0, unlockHint: null,
    unlockMsg: null, bounces: 3,
    desc: 'Rebondit sur les bords',
  },
  artifice: {
    label: "Feu d'artifice", emoji: '🎆', col: '#ff3ea5',
    speed: [3, 11], gravity: GRAVITY * 0.7,
    stock: 2, maxStock: 2, recharge: 12,
    unlockScore: 15, unlockHint: '15 pts',
    unlockMsg: "🎆 Feu d'artifice débloqué !",
    fuseTime: 9, blastR: 100, bounces: 2,
    desc: 'Explose en zone',
  },
  laser: {
    label: 'Laser', emoji: '🔴', col: '#7b3ff2',
    speed: [20, 20], gravity: 0,
    stock: 1, maxStock: 1, recharge: 18,
    unlockScore: 30, unlockHint: '30 pts',
    unlockMsg: '🔴 Pointeur Laser débloqué !',
    desc: 'Rayon qui perce tout',
  },
  carton: {
    label: 'Carton', emoji: '📦', col: '#D4A017',
    speed: [4, 19], gravity: GRAVITY * 1.1,
    stock: 1, maxStock: 1, recharge: 28,
    unlockScore: 80, unlockHint: '80 pts',
    unlockMsg: '📦 Carton Magique débloqué !',
    pullR: 165, pullDur: 4.5, bounces: 3,
    desc: 'Aspire les chats proches',
  },
};

export const BASE_PROJ_DEFS = {
  pelote:  { stock:3, maxStock:3, bounces:3, recharge:2 },
  artifice:{ stock:2, maxStock:2, blastR:100, recharge:12 },
  laser:   { stock:1, maxStock:1, recharge:18 },
  carton:  { stock:1, maxStock:1, pullR:165, recharge:28, bounces:3 },
};

export const CAT_TYPES = [
  // ── Chats de base ────────────────────────────────────────────────────────────
  { id:'tabby',   pts:1,  col:'#FF8C00', size:1.0,  w:25, stripes:true,  minLvl:1 },
  { id:'noir',    pts:1,  col:'#1a1a2e', size:1.0,  w:20, stripes:false, minLvl:1 },
  { id:'blanc',   pts:1,  col:'#F5F0E8', size:1.0,  w:20, stripes:false, minLvl:1 },
  { id:'gris',    pts:1,  col:'#9BA7B0', size:1.0,  w:15, stripes:true,  minLvl:1 },
  { id:'fantome', pts:3,  col:'#A8E6FF', size:1.1,  w:8,  stripes:false, minLvl:1 },
  { id:'astro',   pts:5,  col:'#FF8C00', size:1.2,  w:5,  stripes:false, minLvl:1 },
  { id:'rainbow', pts:5,  col:'rainbow', size:1.2,  w:4,  stripes:false, minLvl:1 },
  { id:'micro',   pts:3,  col:'#FF8C00', size:0.42, w:8,  stripes:true,  minLvl:1 },
  { id:'faux',    pts:-2, col:'#C8A97E', size:1.1,  w:5,  stripes:false, minLvl:1 },
  // ── Chats spéciaux (débloqués par niveau) ────────────────────────────────────
  { id:'zigzag',   pts:2,  col:'#E67E22', size:0.9,  w:14, stripes:true,  minLvl:2,
    label:'Chat Zigzag',   hint:'Oscille horizontalement' },
  { id:'rapide',   pts:2,  col:'#E74C3C', size:0.62, w:10, stripes:false, minLvl:3,
    label:'Chat Rapide',   hint:'3× plus vite !' },
  { id:'bouclier', pts:4,  col:'#3498DB', size:1.1,  w:7,  stripes:false, minLvl:4, hp:2,
    label:'Chat Bouclier', hint:'2 coups pour l\'attraper' },
  { id:'furtif',   pts:5,  col:'#8E44AD', size:0.9,  w:5,  stripes:false, minLvl:5,
    label:'Chat Furtif',   hint:'Frappe quand il est visible !' },
  { id:'boss',     pts:15, col:'#C0392B', size:2.1,  w:0,  stripes:true,  minLvl:6, hp:3,
    label:'LE BOSS',       hint:'3 HP — bonne chance !' },
  // ── Chats attaquants ──────────────────────────────────────────────────────────
  { id:'crachat',  pts:3,  col:'#3dc47e', size:0.88, w:8,  stripes:false, minLvl:3,
    label:'Crâcheur',      hint:'Crache des boules de poils !' },
  { id:'griffeur', pts:5,  col:'#FF6B35', size:1.05, w:5,  stripes:true,  minLvl:4,
    label:'Griffeur',      hint:'Fonce vers toi !' },
  { id:'medecin',  pts:5,  col:'#27AE60', size:0.9,  w:3,  stripes:false, minLvl:3,
    label:'Médecin',       hint:'+1 ❤️ !', heals:true },
  // ── Chats de race ─────────────────────────────────────────────────────────────
  { id:'siamois',  pts:3,  col:'#F5DCBA', size:1.0,  w:18, stripes:false, minLvl:1,
    label:'Siamois',       hint:'Regard de saphir envoûtant' },
  { id:'sphynx',   pts:4,  col:'#C8A882', size:0.95, w:15, stripes:false, minLvl:1,
    label:'Sphynx',        hint:'Chat nu, regard perçant' },
  { id:'persan',   pts:4,  col:'#F0E6D3', size:1.1,  w:15, stripes:false, minLvl:1,
    label:'Persan',        hint:'Poil ultra-long et majestueux' },
  { id:'scottish', pts:5,  col:'#B8C4CC', size:1.0,  w:12, stripes:true,  minLvl:1,
    label:'Scottish Fold', hint:'Oreilles repliées trop mignonnes' },
  { id:'bengal',   pts:6,  col:'#D4A55A', size:1.05, w:12, stripes:true,  minLvl:1,
    label:'Bengal',        hint:'Rosettes léopard sauvages' },
  // ── Chats-professions ────────────────────────────────────────────────────────
  { id:'pompier',   pts:4, col:'#CC3300', size:1.0,  w:10, stripes:false, minLvl:3,
    label:'Chat Pompier',   hint:'Lutte contre les incendies !' },
  { id:'boulanger', pts:3, col:'#E8C9A0', size:1.0,  w:10, stripes:false, minLvl:2,
    label:'Chat Boulanger', hint:'Spécialiste des croque-mitons' },
  { id:'ninja',     pts:5, col:'#1A1A1A', size:0.9,  w:7,  stripes:false, minLvl:4,
    label:'Chat Ninja',     hint:"Insaisissable... jusqu'ici" },
  { id:'detective', pts:4, col:'#7F8C8D', size:1.0,  w:8,  stripes:false, minLvl:3,
    label:'Chat Détective', hint:'Il a flairé la pelote' },
  { id:'pirate',    pts:5, col:'#D4A55A', size:1.05, w:7,  stripes:true,  minLvl:4,
    label:'Chat Pirate',    hint:'Arrr, attrape-moi si tu peux !' },
  { id:'policier',  pts:4, col:'#2C5282', size:1.0,  w:9,  stripes:false, minLvl:2,
    label:'Chat Policier',  hint:'Stop ! Laisse-toi attraper !' },
  { id:'magicien',  pts:5, col:'#553C9A', size:1.0,  w:8,  stripes:false, minLvl:3,
    label:'Chat Magicien',  hint:'Abracadabra !' },
  { id:'cowboy',    pts:4, col:'#C8893C', size:1.05, w:9,  stripes:false, minLvl:2,
    label:'Chat Cowboy',    hint:'Yeehaw !' },
  { id:'viking',    pts:5, col:'#8C6040', size:1.1,  w:7,  stripes:false, minLvl:3,
    label:'Chat Viking',    hint:'Par Odin !' },
  { id:'sorciere',  pts:5, col:'#4A2078', size:1.0,  w:7,  stripes:false, minLvl:3,
    label:'Chat Sorcière',  hint:'Double double toil and trouble !' },
  { id:'marin',     pts:3, col:'#1A3A5C', size:0.95, w:9,  stripes:false, minLvl:2,
    label:'Chat Marin',     hint:'Moussaillon !' },
  { id:'gamer',     pts:4, col:'#2D3748', size:1.0,  w:8,  stripes:false, minLvl:3,
    label:'Chat Gamer',     hint:'GG WP !' },
  { id:'scientifique', pts:5, col:'#E2E8F0', size:1.0, w:7, stripes:false, minLvl:4,
    label:'Chat Scientifique', hint:'Pour la science !' },
  { id:'artiste',   pts:4, col:'#F687B3', size:1.0,  w:8,  stripes:false, minLvl:2,
    label:'Chat Artiste',   hint:"C'est de l'art !" },
  { id:'jardinier', pts:3, col:'#48BB78', size:1.0,  w:9,  stripes:false, minLvl:2,
    label:'Chat Jardinier', hint:'Bloom bloom !' },
  { id:'chevalier', pts:6, col:'#718096', size:1.1,  w:6,  stripes:false, minLvl:5,
    label:'Chat Chevalier', hint:"Pour l'honneur !" },
  { id:'musicien',  pts:4, col:'#ED8936', size:1.0,  w:8,  stripes:false, minLvl:3,
    label:'Chat Musicien',  hint:'🎵 Miaou en do majeur' },
  { id:'cuisinier', pts:4, col:'#F6E05E', size:1.0,  w:8,  stripes:false, minLvl:2,
    label:'Chat Cuisinier', hint:'Bon appétit !' },
  { id:'clown',     pts:3, col:'#FEB2B2', size:1.0,  w:10, stripes:false, minLvl:2,
    label:'Chat Clown',     hint:'Honnnn honnnn !' },
  { id:'robot',     pts:6, col:'#A0AEC0', size:1.05, w:5,  stripes:false, minLvl:5,
    label:'Chat Robot',     hint:'BEEP BOOP' },
  { id:'sportif',   pts:3, col:'#FC8181', size:0.95, w:9,  stripes:false, minLvl:2,
    label:'Chat Sportif',   hint:'Allez !' },
  { id:'professeur',pts:4, col:'#2B6CB0', size:1.0,  w:8,  stripes:false, minLvl:3,
    label:'Chat Professeur',hint:'Interrogation surprise !' },
  { id:'facteur',   pts:3, col:'#ECC94B', size:1.0,  w:9,  stripes:false, minLvl:2,
    label:'Chat Facteur',   hint:'Courrier spécial !' },
  { id:'samourai',  pts:7, col:'#742A2A', size:1.1,  w:5,  stripes:false, minLvl:6,
    label:'Chat Samouraï',  hint:'Bushido !' },
  { id:'infirmier', pts:4, col:'#BEE3F8', size:1.0,  w:8,  stripes:false, minLvl:2,
    label:'Chat Infirmier', hint:'Prenez soin de vous !' },
  // ── Chats super-héros ────────────────────────────────────────────────────────
  { id:'batman',    pts:7, col:'#1A1A1A', size:1.05, w:5, stripes:false, minLvl:4,
    label:'Chat Batman',    hint:'Justicier de la nuit miaou' },
  { id:'superman',  pts:6, col:'#1D8FFF', size:1.0,  w:5, stripes:false, minLvl:3,
    label:'Chat Superman',  hint:'Vol et super force !' },
  { id:'spiderman', pts:6, col:'#E50914', size:0.95, w:5, stripes:false, minLvl:3,
    label:'Chat Spiderman', hint:'Lance des toiles de poils' },
  { id:'flash',     pts:5, col:'#FFE600', size:0.9,  w:6, stripes:false, minLvl:3,
    label:'Chat Flash',     hint:'Trop rapide pour la pelote' },
  { id:'hulk',      pts:8, col:'#3DC47E', size:1.25, w:3, stripes:false, minLvl:5,
    label:'Chat Hulk',      hint:'Smash ! Encaisse les coups' },
  { id:'catwoman',  pts:6, col:'#2A1B4A', size:0.95, w:5, stripes:false, minLvl:4,
    label:'Chat Catwoman',  hint:'Rapide et insaisissable' },
];

export const OBJECT_TYPES = [
  { id:'plume',      label:'Plume',         col:'#C8B4E8', isObject:true, isNeutral:true, size:0.55, baseVy:0.6,  pts:0, w: 28 },
  { id:'souris',     label:'Jouet-souris',  col:'#C0B0A0', isObject:true, isNeutral:true, size:0.7,  baseVy:1.1,  pts:1, w: 28 },
  { id:'bombe',      label:'Bombe',         col:'#2C3E50', isObject:true, isTrap:true, trapKind:'bomb',    size:0.85, baseVy:1.3,  pts:0, w: 12 },
  { id:'chien',      label:'Petit chien',   col:'#9C5A2A', isObject:true, isTrap:true, trapKind:'dog',     size:0.95, baseVy:1.2,  pts:0, w: 7  },
  { id:'flaque',     label:'Flaque',        col:'#5BB6E8', isObject:true, isTrap:true, trapKind:'puddle',  size:0.85, baseVy:0.95, pts:0, w: 8  },
  { id:'piment',     label:'Piment',        col:'#E63946', isObject:true, isTrap:true, trapKind:'chili',   size:0.7,  baseVy:1.4,  pts:0, w: 5  },
  { id:'aspirateur', label:'Aspirateur',    col:'#7B7B8E', isObject:true, isTrap:true, trapKind:'vacuum',  size:1.0,  baseVy:1.0,  pts:0, w: 5  },
];

export const CAT_LABELS = {
  tabby:'Chat Tigré', noir:'Chat Noir', blanc:'Chat Blanc', gris:'Chat Gris',
  fantome:'Fantôme', astro:'Astronaute', rainbow:'Arc-en-Ciel', micro:'Micro-Chat',
  faux:'Chien déguisé',
};

export const CAT_CATEGORIES = {
  tabby:'Commun', noir:'Commun', blanc:'Commun', gris:'Commun',
  fantome:'Spécial', astro:'Spécial', rainbow:'Spécial', micro:'Spécial', faux:'Piège',
  zigzag:'Rare', rapide:'Rare', bouclier:'Rare', furtif:'Rare', boss:'Boss',
  crachat:'Attaquant', griffeur:'Attaquant', medecin:'Attaquant',
  siamois:'Race', sphynx:'Race', persan:'Race', scottish:'Race', bengal:'Race',
  pompier:'Profession', boulanger:'Profession', ninja:'Profession', detective:'Profession', pirate:'Profession',
};

export const CAT_CATCOLS = {
  Commun:'#9BA7B0', Spécial:'#26c6f7', Piège:'#FF4444',
  Rare:'#7b3ff2', Boss:'#C0392B', Attaquant:'#FF6B35', Race:'#ffce3a', Profession:'#3DC47E',
};

export const UPGRADES = [
  // Artilleur
  { id:'bounce2',       family:'Artilleur', emoji:'🧶', col:'#FF6B35', req:'pelote',
    label:'Élastique++',        desc:'Pelote rebondit 2× de plus',
    apply:()=>{ PROJ_DEFS.pelote.bounces=(PROJ_DEFS.pelote.bounces||3)+2; } },
  { id:'blast30',       family:'Artilleur', emoji:'💥', col:'#FF6B35', req:'artifice',
    label:'Méga-Blast',         desc:'Explosion +30px de rayon',
    apply:()=>{ PROJ_DEFS.artifice.blastR+=30; } },
  { id:'artifice_dist', family:'Artilleur', emoji:'🎆', col:'#FF6B35', req:'artifice',
    label:'Longue portée',      desc:"Feu d'artifice explose 60px plus loin", max:3,
    apply:()=>{ upgradeFlags.artificeDistBonus=(upgradeFlags.artificeDistBonus||0)+60; } },
  { id:'artifice_stock',family:'Artilleur', emoji:'🎆', col:'#FF6B35', req:'artifice',
    label:"+1 Feu d'artifice", desc:'+1 munition en réserve', max:3,
    apply:()=>{ PROJ_DEFS.artifice.maxStock++; PROJ_DEFS.artifice.stock++; } },
  { id:'carton_big',    family:'Artilleur', emoji:'📦', col:'#FF6B35', req:'carton',
    label:'Méga-Carton',        desc:'Carton aspire +70px de plus',
    apply:()=>{ PROJ_DEFS.carton.pullR+=70; } },
  { id:'pelote_bounce', family:'Artilleur', emoji:'🧶', col:'#FF6B35', req:'pelote',
    label:'Hyper-Rebond',       desc:"Pelote ne perd jamais d'énergie", max:1,
    apply:()=>{ upgradeFlags.peloteNoDampen=true; } },
  // Sniper
  { id:'laser_wide',    family:'Sniper', emoji:'🔴', col:'#7B3FF2', req:'laser',
    label:'Laser XXL',          desc:'Laser 2× plus large',
    apply:()=>{ state.laserHitWidth+=8; } },
  { id:'recharge_fast', family:'Sniper', emoji:'⚡', col:'#7B3FF2',
    label:'Turbo-Recharge',     desc:'Recharge 25% plus rapide',
    apply:()=>{ for(const id of TYPE_ORDER) PROJ_DEFS[id].recharge*=0.75; } },
  { id:'pelote_stock',  family:'Sniper', emoji:'🧶', col:'#7B3FF2', req:'pelote',
    label:'+1 Pelote',          desc:'+1 pelote en réserve', max:3,
    apply:()=>{ PROJ_DEFS.pelote.maxStock++; PROJ_DEFS.pelote.stock++; } },
  { id:'slow_aim',      family:'Sniper', emoji:'🎯', col:'#7B3FF2',
    label:'Visée Zen',          desc:'Ralenti ×0.5 pendant la visée', max:1,
    apply:()=>{ upgradeFlags.slowAim=true; } },
  { id:'laser_cd',      family:'Sniper', emoji:'🔴', col:'#7B3FF2', req:'laser',
    label:'Laser Express',      desc:'Laser recharge 40% plus vite', max:2,
    apply:()=>{ PROJ_DEFS.laser.recharge*=0.6; } },
  // Chanceux
  { id:'lucky_rate',    family:'Chanceux', emoji:'⭐', col:'#FFCE3A',
    label:'Porte-Bonheur',      desc:'Chats lucky 2× plus fréquents',
    apply:()=>{ upgradeFlags.luckyRate=(upgradeFlags.luckyRate||0.05)*2; } },
  { id:'combo_time',    family:'Chanceux', emoji:'🔥', col:'#FFCE3A',
    label:'Combo Durable',      desc:'Le combo tient 1.5s de plus',
    apply:()=>{ upgradeFlags.comboBonusTime=(upgradeFlags.comboBonusTime||0)+1.5; } },
  { id:'lucky_mult',    family:'Chanceux', emoji:'🌟', col:'#FFCE3A',
    label:'Jackpot',            desc:'Chats lucky valent +1× (cumul)', max:4,
    apply:()=>{ upgradeFlags.luckyMult=(upgradeFlags.luckyMult||5)+1; } },
  { id:'bonus_pts',     family:'Chanceux', emoji:'✨', col:'#FFCE3A',
    label:'Bonus Chat',         desc:'+1 point par chat attrapé', max:4,
    apply:()=>{ upgradeFlags.bonusPts=(upgradeFlags.bonusPts||0)+1; } },
  // Survivant
  { id:'max_life',      family:'Survivant', emoji:'❤️', col:'#3DC47E',
    label:'+1 Cœur Max',        desc:'Vie maximum +1 (et +1 vie maintenant)', max:4,
    apply:()=>{ MAX_LIVES++; lives=Math.min(lives+1,MAX_LIVES); updateHUD(); } },
  { id:'slowmo_early',  family:'Survivant', emoji:'🐌', col:'#3DC47E',
    label:'Réflexes++',         desc:'Slow-mo déclenché dès 2 vies restantes', max:1,
    apply:()=>{ upgradeFlags.slowMoLives=2; } },
  { id:'regen',         family:'Survivant', emoji:'💚', col:'#3DC47E',
    label:'Régénération',       desc:'Récupère 1❤️ tous les 12 chats attrapés', max:1,
    apply:()=>{ upgradeFlags.regen=true; } },
  { id:'shield',        family:'Survivant', emoji:'🛡️', col:'#3DC47E',
    label:'Bouclier',           desc:'Le prochain chat raté ne compte pas', max:1,
    apply:()=>{ upgradeFlags.shield=true; } },
];
